
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action ArchivoAction;

	private global::Gtk.Action AbrirAction;

	private global::Gtk.Action GuardarAction;

	private global::Gtk.Action GuardarComoAction;

	private global::Gtk.Action CerrarAction;

	private global::Gtk.Action EditAction;

	private global::Gtk.Action BuildAndDebugAction;

	private global::Gtk.Action newAction;

	private global::Gtk.Action openAction;

	private global::Gtk.Action saveAction;

	private global::Gtk.Action LexicoAction;

	private global::Gtk.Action SintacticoAction;

	private global::Gtk.Action SemanticoAction;

	private global::Gtk.Action CompilarAction;

	private global::Gtk.Action LexicoAction1;

	private global::Gtk.Action SintacticoAction1;

	private global::Gtk.Action SemanticoAction1;

	private global::Gtk.Action HashTableAction;

	private global::Gtk.Action CdigoIntermedioAction;

	private global::Gtk.Action ErroresLexicosAction;

	private global::Gtk.Action ErroresSintacticosAction;

	private global::Gtk.Action ErroresSemanticosAction;

	private global::Gtk.Action ResultadosAction;

	private global::Gtk.Action Action;

	private global::Gtk.Action LexicoAction2;

	private global::Gtk.Action SemanticoAction2;

	private global::Gtk.Action SintacticoAction2;

	private global::Gtk.Action EjecucinAction;

	private global::Gtk.Action saveAsAction;

	private global::Gtk.Action EjecutarAction;

	private global::Gtk.Action EjecutarAction5;

	private global::Gtk.Action EjecutarAction6;

	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox3;

	private global::Gtk.MenuBar menubar3;

	private global::Gtk.VSeparator vseparator1;

	private global::Gtk.Toolbar toolbar1;

	private global::Gtk.MenuBar menubar5;

	private global::Gtk.VSeparator vseparator3;

	private global::Gtk.TextView textview5;

	private global::Gtk.HBox hbox1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView textview1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView textview3;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Notebook notebook2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow2;

	private global::Gtk.TextView textview9;

	private global::Gtk.Label label5;

	private global::Gtk.ScrolledWindow GtkScrolledWindow7;

	private global::Gtk.TreeView treeview1;

	private global::Gtk.Label label6;

	private global::Gtk.ScrolledWindow GtkScrolledWindow8;

	private global::Gtk.TextView textview10;

	private global::Gtk.Label label7;

	private global::Gtk.ScrolledWindow GtkScrolledWindow9;

	private global::Gtk.NodeView nodeview1;

	private global::Gtk.Label label8;

	private global::Gtk.ScrolledWindow GtkScrolledWindow10;

	private global::Gtk.TextView textview12;

	private global::Gtk.Label label9;

	private global::Gtk.VBox vbox3;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.Notebook notebook1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow3;

	private global::Gtk.TextView textview4;

	private global::Gtk.Label label1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow4;

	private global::Gtk.TextView textview6;

	private global::Gtk.Label label2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow5;

	private global::Gtk.TextView textview7;

	private global::Gtk.Label label3;

	private global::Gtk.ScrolledWindow GtkScrolledWindow6;

	private global::Gtk.TextView textview8;

	private global::Gtk.Label label4;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label label10;

	private global::Gtk.Label label11;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.ArchivoAction = new global::Gtk.Action("ArchivoAction", global::Mono.Unix.Catalog.GetString("Archivo"), null, null);
		this.ArchivoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Archivo");
		w1.Add(this.ArchivoAction, null);
		this.AbrirAction = new global::Gtk.Action("AbrirAction", global::Mono.Unix.Catalog.GetString("Abrir"), null, null);
		this.AbrirAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Abrir");
		w1.Add(this.AbrirAction, null);
		this.GuardarAction = new global::Gtk.Action("GuardarAction", global::Mono.Unix.Catalog.GetString("Guardar"), null, null);
		this.GuardarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Guardar");
		w1.Add(this.GuardarAction, null);
		this.GuardarComoAction = new global::Gtk.Action("GuardarComoAction", global::Mono.Unix.Catalog.GetString("Guardar como"), null, null);
		this.GuardarComoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Guardar como");
		w1.Add(this.GuardarComoAction, null);
		this.CerrarAction = new global::Gtk.Action("CerrarAction", global::Mono.Unix.Catalog.GetString("Cerrar"), null, null);
		this.CerrarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Cerrar");
		w1.Add(this.CerrarAction, null);
		this.EditAction = new global::Gtk.Action("EditAction", global::Mono.Unix.Catalog.GetString("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit");
		w1.Add(this.EditAction, null);
		this.BuildAndDebugAction = new global::Gtk.Action("BuildAndDebugAction", global::Mono.Unix.Catalog.GetString("Build and Debug"), null, null);
		this.BuildAndDebugAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Build and Debug");
		w1.Add(this.BuildAndDebugAction, null);
		this.newAction = new global::Gtk.Action("newAction", null, null, "gtk-new");
		w1.Add(this.newAction, null);
		this.openAction = new global::Gtk.Action("openAction", null, null, "gtk-open");
		w1.Add(this.openAction, null);
		this.saveAction = new global::Gtk.Action("saveAction", null, null, "gtk-save");
		w1.Add(this.saveAction, null);
		this.LexicoAction = new global::Gtk.Action("LexicoAction", global::Mono.Unix.Catalog.GetString("Lexico"), null, null);
		this.LexicoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Lexico");
		w1.Add(this.LexicoAction, null);
		this.SintacticoAction = new global::Gtk.Action("SintacticoAction", global::Mono.Unix.Catalog.GetString("Sintactico"), null, null);
		this.SintacticoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Sintactico");
		w1.Add(this.SintacticoAction, null);
		this.SemanticoAction = new global::Gtk.Action("SemanticoAction", global::Mono.Unix.Catalog.GetString("Semantico"), null, null);
		this.SemanticoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Semantico");
		w1.Add(this.SemanticoAction, null);
		this.CompilarAction = new global::Gtk.Action("CompilarAction", global::Mono.Unix.Catalog.GetString("Compilar"), null, null);
		this.CompilarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Compilar");
		w1.Add(this.CompilarAction, null);
		this.LexicoAction1 = new global::Gtk.Action("LexicoAction1", global::Mono.Unix.Catalog.GetString("Lexico"), null, null);
		this.LexicoAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Lexico");
		w1.Add(this.LexicoAction1, null);
		this.SintacticoAction1 = new global::Gtk.Action("SintacticoAction1", global::Mono.Unix.Catalog.GetString("Sintactico"), null, null);
		this.SintacticoAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Sintactico");
		w1.Add(this.SintacticoAction1, null);
		this.SemanticoAction1 = new global::Gtk.Action("SemanticoAction1", global::Mono.Unix.Catalog.GetString("Semantico"), null, null);
		this.SemanticoAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Semantico");
		w1.Add(this.SemanticoAction1, null);
		this.HashTableAction = new global::Gtk.Action("HashTableAction", global::Mono.Unix.Catalog.GetString("Hash Table"), null, null);
		this.HashTableAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Hash Table");
		w1.Add(this.HashTableAction, null);
		this.CdigoIntermedioAction = new global::Gtk.Action("CdigoIntermedioAction", global::Mono.Unix.Catalog.GetString("Código intermedio"), null, null);
		this.CdigoIntermedioAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Código intermedio");
		w1.Add(this.CdigoIntermedioAction, null);
		this.ErroresLexicosAction = new global::Gtk.Action("ErroresLexicosAction", global::Mono.Unix.Catalog.GetString("Errores Lexicos"), null, null);
		this.ErroresLexicosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Errores Lexicos");
		w1.Add(this.ErroresLexicosAction, null);
		this.ErroresSintacticosAction = new global::Gtk.Action("ErroresSintacticosAction", global::Mono.Unix.Catalog.GetString("Errores Sintacticos"), null, null);
		this.ErroresSintacticosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Errores Sintacticos");
		w1.Add(this.ErroresSintacticosAction, null);
		this.ErroresSemanticosAction = new global::Gtk.Action("ErroresSemanticosAction", global::Mono.Unix.Catalog.GetString("Errores Semanticos"), null, null);
		this.ErroresSemanticosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Errores Semanticos");
		w1.Add(this.ErroresSemanticosAction, null);
		this.ResultadosAction = new global::Gtk.Action("ResultadosAction", global::Mono.Unix.Catalog.GetString("Resultados"), null, null);
		this.ResultadosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Resultados");
		w1.Add(this.ResultadosAction, null);
		this.Action = new global::Gtk.Action("Action", null, null, null);
		w1.Add(this.Action, null);
		this.LexicoAction2 = new global::Gtk.Action("LexicoAction2", global::Mono.Unix.Catalog.GetString("Lexico"), null, null);
		this.LexicoAction2.ShortLabel = global::Mono.Unix.Catalog.GetString("Lexico");
		w1.Add(this.LexicoAction2, null);
		this.SemanticoAction2 = new global::Gtk.Action("SemanticoAction2", global::Mono.Unix.Catalog.GetString("Semantico"), null, null);
		this.SemanticoAction2.ShortLabel = global::Mono.Unix.Catalog.GetString("Semantico");
		w1.Add(this.SemanticoAction2, null);
		this.SintacticoAction2 = new global::Gtk.Action("SintacticoAction2", global::Mono.Unix.Catalog.GetString("Sintactico"), null, null);
		this.SintacticoAction2.ShortLabel = global::Mono.Unix.Catalog.GetString("Sintactico");
		w1.Add(this.SintacticoAction2, null);
		this.EjecucinAction = new global::Gtk.Action("EjecucinAction", global::Mono.Unix.Catalog.GetString("Ejecución"), null, null);
		this.EjecucinAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Ejecución");
		w1.Add(this.EjecucinAction, null);
		this.saveAsAction = new global::Gtk.Action("saveAsAction", null, null, "gtk-save-as");
		w1.Add(this.saveAsAction, null);
		this.EjecutarAction = new global::Gtk.Action("EjecutarAction", global::Mono.Unix.Catalog.GetString("Ejecutar"), null, null);
		this.EjecutarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Ejecutar");
		w1.Add(this.EjecutarAction, null);
		this.EjecutarAction5 = new global::Gtk.Action("EjecutarAction5", global::Mono.Unix.Catalog.GetString("Ejecutar"), null, null);
		this.EjecutarAction5.ShortLabel = global::Mono.Unix.Catalog.GetString("Ejecutar");
		w1.Add(this.EjecutarAction5, null);
		this.EjecutarAction6 = new global::Gtk.Action("EjecutarAction6", global::Mono.Unix.Catalog.GetString("Ejecutar"), null, null);
		this.EjecutarAction6.ShortLabel = global::Mono.Unix.Catalog.GetString("Ejecutar");
		w1.Add(this.EjecutarAction6, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.Gravity = ((global::Gdk.Gravity)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar3'><menu name='ArchivoAction' action='ArchivoAction'><menuitem name='AbrirAction' action='AbrirAction'/><menuitem name='GuardarAction' action='GuardarAction'/><menuitem name='GuardarComoAction' action='GuardarComoAction'/><menuitem name='CerrarAction' action='CerrarAction'/></menu><menu name='EditAction' action='EditAction'/><menu name='BuildAndDebugAction' action='BuildAndDebugAction'><menuitem name='LexicoAction2' action='LexicoAction2'/><menuitem name='SemanticoAction2' action='SemanticoAction2'/><menuitem name='SintacticoAction2' action='SintacticoAction2'/><menuitem name='EjecucinAction' action='EjecucinAction'/></menu></menubar></ui>");
		this.menubar3 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar3")));
		this.menubar3.Name = "menubar3";
		this.hbox3.Add(this.menubar3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.menubar3]));
		w2.Position = 0;
		w2.Expand = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vseparator1 = new global::Gtk.VSeparator();
		this.vseparator1.Name = "vseparator1";
		this.hbox3.Add(this.vseparator1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vseparator1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar1\'><toolitem name=\'newAction\' action=\'newAction\'/><tool" +
				"item name=\'openAction\' action=\'openAction\'/><toolitem name=\'saveAction\' action=\'" +
				"saveAction\'/><toolitem name=\'saveAsAction\' action=\'saveAsAction\'/></toolbar></ui" +
				">");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.hbox3.Add(this.toolbar1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.toolbar1]));
		w4.Position = 2;
		w4.Expand = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar5'><menu name='LexicoAction' action='LexicoAction'><menuitem name='EjecutarAction' action='EjecutarAction'/></menu><menu name='SintacticoAction' action='SintacticoAction'><menuitem name='EjecutarAction5' action='EjecutarAction5'/></menu><menu name='SemanticoAction' action='SemanticoAction'><menuitem name='EjecutarAction6' action='EjecutarAction6'/></menu><menu name='CompilarAction' action='CompilarAction'/><menu name='Action' action='Action'/></menubar></ui>");
		this.menubar5 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar5")));
		this.menubar5.Name = "menubar5";
		this.hbox3.Add(this.menubar5);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.menubar5]));
		w5.Position = 3;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vseparator3 = new global::Gtk.VSeparator();
		this.vseparator3.Name = "vseparator3";
		this.hbox3.Add(this.vseparator3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vseparator3]));
		w6.PackType = ((global::Gtk.PackType)(1));
		w6.Position = 4;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.textview5 = new global::Gtk.TextView();
		this.textview5.Sensitive = false;
		this.textview5.CanFocus = true;
		this.textview5.Name = "textview5";
		this.textview5.Editable = false;
		this.textview5.CursorVisible = false;
		this.textview5.Justification = ((global::Gtk.Justification)(1));
		this.hbox3.Add(this.textview5);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.textview5]));
		w7.PackType = ((global::Gtk.PackType)(1));
		w7.Position = 5;
		this.vbox1.Add(this.hbox3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Sensitive = false;
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(2));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView();
		this.textview1.Sensitive = false;
		this.textview1.Name = "textview1";
		this.textview1.Editable = false;
		this.textview1.CursorVisible = false;
		this.textview1.AcceptsTab = false;
		this.textview1.Justification = ((global::Gtk.Justification)(1));
		this.textview1.WrapMode = ((global::Gtk.WrapMode)(3));
		this.GtkScrolledWindow.Add(this.textview1);
		this.hbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.textview3 = new global::Gtk.TextView();
		this.textview3.CanFocus = true;
		this.textview3.Events = ((global::Gdk.EventMask)(2097156));
		this.textview3.Name = "textview3";
		this.GtkScrolledWindow1.Add(this.textview3);
		this.hbox1.Add(this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow1]));
		w12.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.notebook2 = new global::Gtk.Notebook();
		this.notebook2.CanFocus = true;
		this.notebook2.Name = "notebook2";
		this.notebook2.CurrentPage = 3;
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.textview9 = new global::Gtk.TextView();
		this.textview9.CanFocus = true;
		this.textview9.Name = "textview9";
		this.textview9.Editable = false;
		this.GtkScrolledWindow2.Add(this.textview9);
		this.notebook2.Add(this.GtkScrolledWindow2);
		// Notebook tab
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Lexico");
		this.notebook2.SetTabLabel(this.GtkScrolledWindow2, this.label5);
		this.label5.ShowAll();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow7 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow7.Name = "GtkScrolledWindow7";
		this.GtkScrolledWindow7.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow7.Gtk.Container+ContainerChild
		this.treeview1 = new global::Gtk.TreeView();
		this.treeview1.CanFocus = true;
		this.treeview1.Name = "treeview1";
		this.GtkScrolledWindow7.Add(this.treeview1);
		this.notebook2.Add(this.GtkScrolledWindow7);
		global::Gtk.Notebook.NotebookChild w16 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2[this.GtkScrolledWindow7]));
		w16.Position = 1;
		// Notebook tab
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Sintactico");
		this.notebook2.SetTabLabel(this.GtkScrolledWindow7, this.label6);
		this.label6.ShowAll();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow8 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow8.Name = "GtkScrolledWindow8";
		this.GtkScrolledWindow8.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow8.Gtk.Container+ContainerChild
		this.textview10 = new global::Gtk.TextView();
		this.textview10.CanFocus = true;
		this.textview10.Name = "textview10";
		this.GtkScrolledWindow8.Add(this.textview10);
		this.notebook2.Add(this.GtkScrolledWindow8);
		global::Gtk.Notebook.NotebookChild w18 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2[this.GtkScrolledWindow8]));
		w18.Position = 2;
		// Notebook tab
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Semantico");
		this.notebook2.SetTabLabel(this.GtkScrolledWindow8, this.label7);
		this.label7.ShowAll();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow9 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow9.Name = "GtkScrolledWindow9";
		this.GtkScrolledWindow9.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow9.Gtk.Container+ContainerChild
		this.nodeview1 = new global::Gtk.NodeView();
		this.nodeview1.CanFocus = true;
		this.nodeview1.Name = "nodeview1";
		this.GtkScrolledWindow9.Add(this.nodeview1);
		this.notebook2.Add(this.GtkScrolledWindow9);
		global::Gtk.Notebook.NotebookChild w20 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2[this.GtkScrolledWindow9]));
		w20.Position = 3;
		// Notebook tab
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Hash Table");
		this.notebook2.SetTabLabel(this.GtkScrolledWindow9, this.label8);
		this.label8.ShowAll();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow10 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow10.Name = "GtkScrolledWindow10";
		this.GtkScrolledWindow10.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow10.Gtk.Container+ContainerChild
		this.textview12 = new global::Gtk.TextView();
		this.textview12.CanFocus = true;
		this.textview12.Name = "textview12";
		this.GtkScrolledWindow10.Add(this.textview12);
		this.notebook2.Add(this.GtkScrolledWindow10);
		global::Gtk.Notebook.NotebookChild w22 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2[this.GtkScrolledWindow10]));
		w22.Position = 4;
		// Notebook tab
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Código Intermedio");
		this.notebook2.SetTabLabel(this.GtkScrolledWindow10, this.label9);
		this.label9.ShowAll();
		this.vbox2.Add(this.notebook2);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.notebook2]));
		w23.Position = 0;
		this.hbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
		w24.Position = 2;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w25.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.vbox3.Add(this.hseparator1);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hseparator1]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 1;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.textview4 = new global::Gtk.TextView();
		this.textview4.CanFocus = true;
		this.textview4.Name = "textview4";
		this.textview4.Editable = false;
		this.GtkScrolledWindow3.Add(this.textview4);
		this.notebook1.Add(this.GtkScrolledWindow3);
		// Notebook tab
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Errores Lexicos");
		this.notebook1.SetTabLabel(this.GtkScrolledWindow3, this.label1);
		this.label1.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
		this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
		this.textview6 = new global::Gtk.TextView();
		this.textview6.CanFocus = true;
		this.textview6.Name = "textview6";
		this.textview6.Editable = false;
		this.GtkScrolledWindow4.Add(this.textview6);
		this.notebook1.Add(this.GtkScrolledWindow4);
		global::Gtk.Notebook.NotebookChild w30 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.GtkScrolledWindow4]));
		w30.Position = 1;
		// Notebook tab
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Errores Sintacticos");
		this.notebook1.SetTabLabel(this.GtkScrolledWindow4, this.label2);
		this.label2.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow5 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow5.Name = "GtkScrolledWindow5";
		this.GtkScrolledWindow5.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow5.Gtk.Container+ContainerChild
		this.textview7 = new global::Gtk.TextView();
		this.textview7.CanFocus = true;
		this.textview7.Name = "textview7";
		this.GtkScrolledWindow5.Add(this.textview7);
		this.notebook1.Add(this.GtkScrolledWindow5);
		global::Gtk.Notebook.NotebookChild w32 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.GtkScrolledWindow5]));
		w32.Position = 2;
		// Notebook tab
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Errores Semanticos");
		this.notebook1.SetTabLabel(this.GtkScrolledWindow5, this.label3);
		this.label3.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow6 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow6.Name = "GtkScrolledWindow6";
		this.GtkScrolledWindow6.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow6.Gtk.Container+ContainerChild
		this.textview8 = new global::Gtk.TextView();
		this.textview8.CanFocus = true;
		this.textview8.Name = "textview8";
		this.GtkScrolledWindow6.Add(this.textview8);
		this.notebook1.Add(this.GtkScrolledWindow6);
		global::Gtk.Notebook.NotebookChild w34 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.GtkScrolledWindow6]));
		w34.Position = 3;
		// Notebook tab
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Resultados");
		this.notebook1.SetTabLabel(this.GtkScrolledWindow6, this.label4);
		this.label4.ShowAll();
		this.vbox3.Add(this.notebook1);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.notebook1]));
		w35.Position = 1;
		this.vbox1.Add(this.vbox3);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox3]));
		w36.Position = 2;
		w36.Expand = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Direccion");
		this.hbox2.Add(this.label10);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label10]));
		w37.Position = 0;
		w37.Expand = false;
		w37.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("[1,0]");
		this.hbox2.Add(this.label11);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label11]));
		w38.Position = 2;
		w38.Expand = false;
		w38.Fill = false;
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w39.Position = 3;
		w39.Expand = false;
		w39.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1071;
		this.DefaultHeight = 393;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.AbrirAction.Activated += new global::System.EventHandler(this.OnAbrirActionActivated);
		this.GuardarAction.Activated += new global::System.EventHandler(this.OnGuardarActionActivated);
		this.GuardarComoAction.Activated += new global::System.EventHandler(this.OnGuardarComoActionActivated);
		this.CerrarAction.Activated += new global::System.EventHandler(this.OnCerrarActionActivated);
		this.newAction.Activated += new global::System.EventHandler(this.OnNewActionActivated);
		this.openAction.Activated += new global::System.EventHandler(this.OnOpenActionActivated);
		this.saveAction.Activated += new global::System.EventHandler(this.OnSaveActionActivated);
		this.saveAsAction.Activated += new global::System.EventHandler(this.OnSaveAsActionActivated);
		this.EjecutarAction.Activated += new global::System.EventHandler(this.OnEjecutarActionActivated);
		this.EjecutarAction5.Activated += new global::System.EventHandler(this.OnEjecutarAction1Activated);
		this.EjecutarAction6.Activated += new global::System.EventHandler(this.OnEjecutarSemantico);
		this.textview3.PasteClipboard += new global::System.EventHandler(this.OnTextview3PasteClipboard);
		this.textview3.InsertAtCursor += new global::Gtk.InsertAtCursorHandler(this.OnTextview3InsertAtCursor);
		this.textview3.CutClipboard += new global::System.EventHandler(this.OnTextview3CutClipboard);
		this.textview3.MoveCursor += new global::Gtk.MoveCursorHandler(this.OnTextview3MoveCursor);
		this.textview3.MoveFocus += new global::Gtk.MoveFocusHandler(this.OnTextview3MoveFocus);
		this.textview3.ScrollEvent += new global::Gtk.ScrollEventHandler(this.OnTextview3ScrollEvent);
		this.textview3.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler(this.OnTextview3KeyReleaseEvent);
	}
}
